title: Writings on the Board
description: '"Writings on the Board" is a collection of (in)evitable Whys.'
theme: just-the-docs
repository: andreineculau/writingsontheboard

url: https://andreineculau.github.io/writingsontheboard

# permalink: pretty
# search_enabled: true
# heading_anchors: true

# footer_content: '"Writings on the Board" is a collection of (in)evitable Whys.'
# last_edit_timestamp: true
# last_edit_time_format: "%F %T"

gh_edit_link: true
gh_edit_repository: https://github.com/andreineculau/writingsontheboard
gh_edit_branch: master
gh_edit_view_mode: edit

plugins:
  - jekyll-seo-tag
