title: Writings on the Board
description: "Writings on the Board" is a collection of (in)evitable Whys.
theme: just-the-docs

url: https://andreinecualu.github.io/writingsontheboard

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
