title: Writings on the Board
description: '"Writings on the Board" is a collection of (in)evitable Whys.'
theme: just-the-docs
repository: andreineculau/writingsontheboard

url: https://andreineculau.github.io/writingsontheboard/
baseurl: /writingsontheboard

# permalink: pretty
heading_anchors: true

footer_content: '"Writings on the Board" is a collection of (in)evitable Whys.'
last_edit_timestamp: true
last_edit_time_format: "%F %T"
gh_edit_link: true
gh_edit_repository: https://github.com/andreineculau/writingsontheboard
gh_edit_branch: master
gh_edit_view_mode: edit

plugins:
  - jekyll-seo-tag

logo: assets/images/logo.webp
favicon_ico: assets/images/logo.ico
mermaid:
  version: 11.12.3
  path: /assets/js/mermaid.esm.min.mjs
enable_copy_code_button: true

# https://just-the-docs.com/docs/configuration/#document-collections
collections:
  tests:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:
  collections:
    tests:
      name: Tests
